### ISSUE TITLE
mockClient method arguments types are not properly defined (typescript)

### ISSUE THREAD

**Issue by widedA** [tulios/mappersmith#157]
```
import forge from 'mappersmith'
import { mockClient } from 'mappersmith/test'

const github = forge({
  clientId: 'github',
  host: 'https://status.github.com',
  resources: {
    Status: {
      current: { path: '/api/status.json' },
    },
    Message: {
      messages: { path: '/api/messages.json' },
      lastMessage: { path: '/api/last-message.json' },
    },
  },
})

const mock = mockClient<typeof github>(github)
  .resource('Status')
  .method('current')
  .with({ id: 'abc' })
  .response({ allUsers: [] })
  .assertObject()
```
The above code is causing the following error
> Argument of type '"current"' is not assignable to parameter of type 'never'.ts(2345)

It might be that the method arguments types are not defined correctly

**Comment by Yurickh** [comment]
For this one I have two proposed fixes that _will_ affect the way this is consumed.

## Option A: The Generic Extension
```js
const mock = mockClient<typeof github, "Status">(github)
  .resource("Status")
  .method("current")
  .with({ id: "abc" })
  .response({ allUsers: [] })
  .assertObject();
```
In this one, we pass a new generic parameter to `mockClient`, specifying which resource we want to mock.

### Advantage
- The order in which `resource` and `method` are applied don't change the final result, so the code "behaves" more like the JS counterpart.

### Caveats
- We press for repetition (`<typeof github, "Status">` + `.resource("Status")`)

## Option B: The smart derivation
```js
const mock = mockClient(github)
  .resource("Status")
  .method("current")
  .with({ id: "abc" })
  .response({ allUsers: [] })
  .assertObject();
```

### Advantage
- Don't require knowledge of generics, code looks more like the JS counterpart

### Caveats
- In order to derive the resource type, it is enforced that `resource` is declared before `method`, otherwise we fall in the same problem:

```js
const mock = mockClient(github)
  .method("current") // Argument of type '"current"' is not assignable to parameter of type 'never'
  .resource("Status")
  .with({ id: "abc" })
  .response({ allUsers: [] })
  .assertObject();
```

I don't have a hard opinion on which path to follow, but I can open a PR for either fix right way. Would love to know the opinion of the core maintainers :)~

c.c @tulios

**Comment by Yurickh** [comment]
It's worth noting that the code that attends to `Option B` also allows for fixing the same problem using `Option A`'s solution 😅
So I guess the question is if we want to push for generics, or allow "smart" derivation to a point.

**Comment by tulios** [comment]
I like the option B)

I will try to reserve some time to go over the PR, thanks @Yurickh
