### ISSUE TITLE
MockClient responses should be clones

### ISSUE THREAD

**Issue by Nevon** [tulios/mappersmith#158]
I just got bitten by a tricky test failure where the code under test was mutating the response from mappersmith, which actually caused the fixture I passed to my mock to be mutated.

Example:

```javascript
const fixture = ['item']

const mock = () => mockClient(apiClient).resource('Foo').method('list').response(fixture)

const functionUnderTest = async () => {
  const response = await apiClient.Foo.list().then(response => response.data())
  return response.shift()
}

const testFunction = async () => {
  mock()
  const items = await functionUnderTest()
  expect(items).toHaveLength(1)
}

test('first test', testFunction) // this will pass
test('second test', testFunction) // this will fail
```

This is because the Mappersmith mock returns a direct reference to the same object, rather than a copy of it.

**Comment by Nevon** [comment]
This is a bit trickier than expected. Added a test case that's failing anyway.

**Comment by klippx** [comment]
This is tricky indeed. In order to do this right, we would need to add something like `lodash.clone` as a dependency. Which could be fine? But there is the small fact that mappersmith is (technically) zero dependency so that would be a big thing. It shamelessly copies from some libs just to stay that way, in some cases.

If we are to follow earlier habits then we would copy paste `lodash.clone` instead of creating a dependency. Which is not something I personally like.

I would vote for breaking the glass wall and allowing `lodash.clone` as a dependency, if we want to solve this properly. Unless someone is keen on writing their own deep clone in JS?
