### ISSUE TITLE
Ssl authentication doc contribution

### ISSUE THREAD

**Issue by chualanagit** [tulios/mappersmith#189]
Recently I struggled with configuring SSL authentication for my Kafka schema registry as described [here](https://github.com/tulios/mappersmith#http) because I have a CA, a P12, and a password that are needed for authentication. It was not clear for me how I would configure from reading the documentation. I'd like to contribute to the doc to make it more clear.

**Comment by Nevon** [comment]
Great that you are willing to make a contribution. What do you have in mind?

I would be wary of trying to document `https.Agent`, since that's a Node API and not a mappersmith API. That said, the Node docs for this are indeed really freaking hard to understand, given that [the options to the Agent constructor are incredibly poorly documented](https://nodejs.org/api/http.html#http_new_agent_options). I'm pretty sure it accepts all the options of [tls.createSecureContext](https://nodejs.org/api/tls.html#tls_tls_createsecurecontext_options), which is why you can pass `cert`, `key` etc. but I can't find any documentation that actually says so.

I think this issue sums it up pretty well: https://github.com/nodejs/node/issues/10203

**Comment by chualanagit** [comment]
That makes sense. my concern about poor documentation is probably for `http.Agent` instead of mappersmith. I'll close the issue.
