### ISSUE TITLE
MockResponse/MockRequest should match regardless of params if responseHandler is defined

### ISSUE THREAD

**Issue by cgklarna** [tulios/mappersmith#229]
I am trying to create a test that does something similar to Jest's mockImplementation. I think if a responseHandler is defined on a `MockRequest`, mappersmith should not care what the params are when deciding if there is a match. Alternatively, there could be a way to specify that the request params should not be considered when looking for a match e.g. `.ignoreWith()` or the like.

Relevant Line:

https://github.com/tulios/mappersmith/blob/0067c23c859043cde345bdf166c8382af1255393/src/mocks/mock-request.js#L96

**Comment by klippx** [comment]
`responseHandler` is not for matching, it is only for setting response data _after_ the fact that the mock has been matched. Or do I misunderstand? Perhaps you can give an example how you use `mockRequest` and what you expected?

**Comment by klippx** [comment]
This use case is supported:

```
  it('allows for response to be a function of request body', async () => {
    mockClient(client)
      .resource('Blog')
      .method('post')
      .with({
        body: m.anything(),
      })
      .response((request) => request.body())
      .assertObject()

    const response = await client.Blog.post({ body: { true: false } })

    expect(response.data()).toEqual({ true: false })
  })
```

You just have to specify `.with({ body: m.anything() })`. It is an extra line, but it makes it more explicit in the test what is happening. I don't think a special case should happen just because `responseHandler` was used. 

However, it is a point of discussion whether or not if `.with` should default to `{ body: m.anything(), headers: m.anything() }` if it is not specified. The difference is that then it would not be a special case when `responseHandler` is used but a global default behaviour of `MockResource`.

If so, then this should pass:

```
  it('allows for response to be a function of request body', async () => {
    mockClient(client)
      .resource('Blog')
      .method('post')
      .response((request) => request.body())
      .assertObject()

    const response = await client.Blog.post({ body: { true: false }, headers: { foo: 'bar' } })

    expect(response.data()).toEqual({ true: false })
  })
```

**Comment by klippx** [comment]
Related issue #152
