### ISSUE TITLE
How to forge a typed Mappersmith client?

### ISSUE THREAD

**Issue by guidolodetti** [tulios/mappersmith#290]
Hey there 👋

I was wondering what was the best way to forge a Mappersmith client in a TypeScript way. We use it extensively at our company, but so far I could not find a good solution.

Thank you,

Guido

**Comment by Nevon** [comment]
Maybe @klippx has some good thoughts, since he's been converting Mappersmith to Typescript. But what kind of typing is it that you're thinking of, if you could dream up some pseudocode to show what you would imagine?

To me, the biggest challenge is in the response body type. Currently I don't know if it's returning `unknown` or maybe `any`. But even if we imagine some kind of generic where you pass in a `ResponseBody` type for each method, unless Mappersmith actually parses the response and validates at runtime that it matches the expected type, at the end of the day all it's gonna do is cast to your `ResponseBody` type. So it would be a little nicer, in the sense that you wouldn't have to manually cast to your expected response type, but it wouldn't really make your code any safer.

The alternative would be if you had a way for a middleware to change the type of the response. Then you could implement runtime parsing, in which case you would get type safety. For example, I could imagine a middleware that uses https://github.com/fabien0102/ts-to-zod to generate a parser from a generic type, and then uses that parser on the response. What mappersmith would need to do to enable that is have a way for a middleware to alter the response type.

**Comment by guidolodetti** [comment]
Hi @Nevon! You got it right:
> To me, the biggest challenge is in the response type

I would love to have something like this:

```typescript
forge({
    resources: {
      Transaction: {
        getTransactionData<{ THIS IS MY RESPONSE OBJECT }>: {
          path: '/example',
        },
      },
    },
  })
```

**Comment by klippx** [comment]
I would point you to this issue: https://github.com/tulios/mappersmith/issues/263
