### ISSUE TITLE
TimeoutMiddleware stops working when enabling useSocketConnectionTimeout

### ISSUE THREAD

**Issue by antonio-iodice** [tulios/mappersmith#371]
Hi all, I am facing a weird issue. I enabled useSocketConnectionTimeout option in the HTTP gateway. Everything seems to work fine, expect that in production timeout stopped being triggered at all.
```
forge({
      host,
      ignoreGlobalMiddleware: true
      middleware: [
        ErrorMiddleware,
        TimeoutMiddleware(timeout),
      ],
      })
```

Unfortunately I haven't been able to reproduce this locally, so I am not sure if it's a bug or something I am missing. Could you think of anything related to useSocketConnectionTimeout that might influence or disable the timeoutMiddleware?

EDIT: One additional information that might potentially influence this. In production environments we are tunneling requests through a proxy.

**Comment by klippx** [comment]
I haven't seen this myself, but my guess is that it could be due to this code in HTTP gateway:

```ts
    if (timeout) {
      if (!httpOptions.useSocketConnectionTimeout) {
        httpRequest.setTimeout(timeout)
      }

      httpRequest.on('timeout', () => {
        this.canceled = true
        httpRequest.abort()
        const error = createTimeoutError(`Timeout (${timeout}ms)`)
        this.dispatchClientError(error.message, error)
      })
    }
```
If `useSocketConnectionTimeout` is true then the manual `setTimeout` will not happen. Then it is up to node implementation to emit a `timeout`, this might vary between node version you are using.

Please try to debug this by logging in this code and see if you can see timeout being triggered with `useSocketConnectionTimeout` both as true and false. You can also experiment with different node versions to see which one works, I think this can be different in 10, 12, 14, 16 etc.

**Comment by antonio-iodice** [comment]
I cannot reproduce it locally so yes, I see timeouts being triggered when using locally. In production environments, where I am tunneling connections through a proxy I don't see timeouts being triggered.
Also, according to the node documentation, the only difference between setting timeout via the timeout property and the setTimeout function is that the former sets it before the socket connection is even established, while the latter waits for the socket to be connected.
https://nodejs.org/api/http.html#httprequesturl-options-callback
