### ISSUE TITLE
Why does "Network error" have 400 status code?

### ISSUE THREAD

**Issue by kabirbaidhya** [tulios/mappersmith#374]
Hi folks, 

I noticed that mappersmith responds with errors seeming to be connectivity or "Network error"s with `400` status code. And I see that you're treating it as an expected behaviour here:
- https://github.com/tulios/mappersmith/blob/90f0382ce2ef749b1778ad6b377a401330682a53/spec/integration/node/integration.spec.js#L31-L41
- https://github.com/tulios/mappersmith/blob/90f0382ce2ef749b1778ad6b377a401330682a53/src/gateway.js#L52

Any reason why these are considered a `400` error? 
This is confusing to me as these requests never seem to reach the server and at the first glance, if you only check the error code, it misleads you to consider the error is an actual HTTP 400 error from the backend.

**Comment by klippx** [comment]
Historically, the project started with a general 400 as it is simply the first code that is considered an error (4xx+ family). 

This makes no sense from case to case, and we need more cases covered [here](https://github.com/tulios/mappersmith/blob/e6f633e8f57cf4eba2661ece47c0bf9d3cd9ade7/src/gateway.ts#L94C3-L100)
- For instance, `408` has been added, but in my opinion that was done too cautiously, since it is an option and defaulting to false, so you need to enable it to get a sensible default. I guess this was done like this to be backwards compatible.

**Comment by salesfelipe** [comment]
Just wanted to share one experience that I had on this topic. I've enabled the config to enable 408 as status code and then started noticing some doubled requests to our services. It turns out that the Browser might retry the request automatically in case of 408, no matter the method. So be mindful of that when you turn it on.  Here is one thread I found about it: 

https://groups.google.com/a/chromium.org/g/chromium-dev/c/urswDsm6Pe0?pli=1

**Comment by klippx** [comment]
@kabirbaidhya To address the issue itself, that's just the design of mappersmith. It always returns or throw a `Response`. So we could set status to `null` in some cases when there was no _actual_ response, or the design of mappersmith could be different and throwing `MappersmithError` that may or may not contain a response. Which would be a very breaking change, I am afraid.

So far it hasn't been a huge pain so I will close this unless you get a ton of +1s then we can at least consider it for a v3 in the future :)
