### ISSUE TITLE
Bug: memory leak with when using Http(s)Agent keepAlive=true

### ISSUE THREAD

**Issue by allanpaiste** [tulios/mappersmith#390]
When using `HttpAgent` with `{keepAlive: true}`, the request socket never gets destroyed which is not taken into account by the code that registers event observers against said socket object. 

This means that this block of code:

https://github.com/tulios/mappersmith/blob/1fdaacc/src/gateway/http.ts#L94-L114

... will evaluate on every request and will - in reality - target same socket object instance.

The result is a valid/concerning node runtime warning that some object is getting overloaded by event observers. 

## Proof

Using modified version of the fist example given in the README as proof:

```typescript
import forge from 'mappersmith';
import {Agent as HttpsAgent} from 'https';

const httpAgent = new HttpsAgent({keepAlive: true});
const github = forge({
  clientId: 'example',
  host: 'https://example.com/',
  gatewayConfigs: {
    HTTP: {configure: () => ({agent: httpAgent})},
  },
  resources: {
    Status: {
      beepBoop: {path: '/'},
    },
  },
});

(async () => {
  for (let i = 0; i < 50; i += 1) {
    github.Status.beepBoop().then(() => {
      process.stdout.write('.');
    });
    await new Promise((resolve) => setTimeout(resolve, 100));
  }
})();
```

### Expected output

```txt
..................................................
```

### Actual output

```txt
.............................(node:39094) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 lookup listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:39094) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connect listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:39094) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 secureConnect listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
.....(node:39094) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 lookup listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:39094) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connect listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:39094) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 secureConnect listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
................
```

## Proposed fix

One can just make sure not to re-register the observers when socket is reused which can be easily detected via request object property:

```typescript
if (!httpRequest.reusedSocket) {
  httpRequest.on('socket', (socket) => {
    // ... redacted
  })
}
```

**Comment by klippx** [comment]
Thanks for reporting this, really well written issue. 

Is there any chance that you would like to try to take your level of contribution to the next level and create a branch containing a spec that reproduces the issue? 🙏 

It would be super appreciated, especially in case you already have a battle tested fix on your end.

**Comment by allanpaiste** [comment]
Hi @klippx!

In an odd twist of fate - I did actually start out with the idea of presenting this issues in form of a pull-request. 

Unfortunately - and that it completely on me - the setup of the test cases for this package uses structure that I'm not familiar with (at least I was having trouble detecthing a setup-execute-assert pattern that I'm accustomed to).

I also had trouble getting the project to install properly (where it got stuck with something with pre-install scripts).

As such: I decided that giving a clear report on the issue and the serious nature of it might be enough for the author(s) (or people more in-tune with the setup of the particular project) to be motivated to quickly tackle the issue themselves.

**Comment by klippx** [comment]
This has been released in 2.43.0!

**Comment by huntharo** [comment]
No response needed

Adding a comment here for future readers to understand the potential impact of this bug.

## Example App Impact

- App uses `mappersmith` indirectly via `@kafkajs/confluent-schema-registry` for parsing Kafka messages
- App is deployed on AWS Lambda
- App has global http / https agent override set to enable keep-alive reuse of sockets (off by default in Node.js for requests made to other services)
- Nominally, the app would process 1k Kafka messages in 5 seconds or less
- When processing infrequent events, allowing the HTTP socket to close, the issue was not apparent
- When processing a backlog of millions of messages, resulting in continuous invokes, keeping the socket open for many minutes, the runtimes would increase from 5 seconds to 500 seconds until the Lamba eventually timed out
  - Note that in this case the payloads were not larger, they simply were invoked one after the other without allowing the Lambda to be idle long enough for the socket that `mappersmith` owned to close

This application saw a 100x increase in runtime due to the accumulation of event emitters on these long-lived sockets.

Thank you so much for the fix!

<img width="1683" alt="image" src="https://github.com/tulios/mappersmith/assets/5617868/baca6f3d-a4a5-4df6-9534-57620c8cc04b">

**Comment by joyrexus** [comment]
@huntharo 

You mention that your app uses **mappersmith** [indirectly](https://github.com/kafkajs/confluent-schema-registry/blob/514391cc997d1ce6f6a3b7aca33d756ed3e8eb3b/src/api/middleware/errorMiddleware.ts#L22) via `@kafkajs/confluent-schema-registry` for parsing Kafka messages and is deployed on AWS Lambda.

That's precisely my scenario.

Just curious if you now periodically see your lambdas logging these `socket hang up` errors?

```
ResponseError: Confluent_Schema_Registry - Error, status 400: socket hang up
    at /var/task/handler.js:46809:108 {
  status: 400,
  unauthorized: false,
  url: 'get https://prod-schema-registry.ops-prod.getbuilt.com/schemas/ids/495'
}
```

We've started observing this and I'm still trying to diagnose. We're running a ["standalone"](https://docs.nestjs.com/faq/serverless#using-standalone-application-feature) nestjs app within the lambda, so trying to determine [if the issue lies there](https://github.com/vercel/next.js/discussions/60148).

**Comment by joyrexus** [comment]
@klippx thanks for the response.

Regarding _"Are you using the fetch or HTTP gateway?"_.

I'm not sure, because we're not using mappersmith directly. Like @huntharo, we're using the [**confluence-schema-registry**](https://github.com/kafkajs/confluent-schema-registry/tree/master?tab=readme-ov-file#confluent-schema-registry) package, which appears to be [using mappersmith as its http agent](https://github.com/search?q=repo%3Akafkajs%2Fconfluent-schema-registry%20mappersmith&type=code).

For context, we're trying to diagnose why we periodically see our lambda's throwing a socket hang up error when attempting to fetch a schema from the registry using this package:

<img width="789" height="709" alt="Image" src="https://github.com/user-attachments/assets/5dc33c5c-e746-432a-aaa4-4a3f3006ace3" />
