### ISSUE TITLE
How can i abort running XHR request?

### ISSUE THREAD

**Issue by Ar2r** [tulios/mappersmith#44]
In jQuery i need to do like this `xhr.abort()`

**Comment by tulios** [comment]
Hi @Ar2r, sorry for the delay. I've discussed the use of `abort` with others and I couldn't find a good solution so far, so, currently, mappersmith doesn't have official "support" to `abort`. But you can have access to the `xhr` object through the `configure` method, something like:

```javascript
import { configs } from 'mappersmith'
configs.gatewayConfigs.XHR = {
  configure(xhr) {
    // save the reference of xhr for latter use
  }
}
```

Since the resource methods returns a `Promise` I'm not sure how to give access to specifics of each gateway request. If you have any suggestions please share.

Thanks
